---
galaxy_info:
  author: lotusnoir
  role_name: apps_conntrack_textfile_exporter
  description: "Deploy a script that collect all established connection to the server via conntrack."
  license: "Apache License, Version 2.0"
  min_ansible_version: "2.8"

  platforms:
    - name: "Ubuntu"
      versions:
        - "focal"
        - "jammy"
        - "noble"
        - "resolute"
    - name: "Debian"
      versions:
        - "buster"
        - "bullseye"
        - "bookworm"
        - "trixie"
    - name: "Rocky"
      versions:
        - "8"
        - "9"
        - "10"
    - name: "OracleLinux"
      versions:
        - "8"
        - "9"
        - "10"

  galaxy_tags:
    - metrics
    - prometheurs
    - conntrack
    - network
    - exporter

dependencies: []
