---
- name: "Set temp dir name"
  ansible.builtin.set_fact:
    _textfile_exporters_temp_dir: "{{ item | basename }}"
  tags:
    - deploy
    - scripts

- name: "Checkout textfile exporter repository locally"
  ansible.builtin.git:
    repo: "{{ item }}"
    dest: "/tmp/{{ _textfile_exporters_temp_dir }}"
    update: true
    # force: true
  register: git_result
  retries: 12
  delay: 10
  until: git_result is success
  delegate_to: localhost
  run_once: true
  tags:
    - deploy
    - scripts

- name: "Copy textfile exporter scripts remotely"
  ansible.builtin.copy:
    src: "/tmp/{{ _textfile_exporters_temp_dir }}/"
    dest: "{{ textfile_exporters_install }}/"
    mode: "0755"
    directory_mode: "0755"
  tags:
    - deploy
    - scripts
